#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

if [ ! -e ./util/install ]; then
  echo "$0 must be run from the top of the project tree"
  exit
fi

if [ -d inst/doc ]; then
  mv inst/doc inst/doc.skip
  echo "NOTE: Disabling vignettes for quick install"
fi

pkg=rpf

rm -f ${pkg}_*.tar.gz
./util/rox
R CMD build .
R CMD INSTALL ${pkg}_*.tar.gz
