#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

if [ ! -x inst/rox ]; then
  echo "$0 must be run from the top of the package directory"
  exit 1
fi

# hm, maybe could store the version here and change the date
# if the version changes? TODO

#today=$(date +%Y-%m-%d)
#perl -pi -e "s/^Date\:.*$/Date: $today/" DESCRIPTION

rm -f man/*.Rd
R --no-restore --no-save --no-readline <<EOF
library(roxygen2)
roxygenize('.')
EOF
